name: base
channels:
  - conda-forge
  - weinbe58
  - bioconda/label/cf201901
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - blas=1.0=openblas
  - bleach=3.3.0=pyhd3eb1b0_0
  - boost=1.73.0=py39h06a4308_12
  - brotli-python=1.0.9=py39h6a678d5_7
  - bwa=0.7.17=h5bf99c6_8
  - bwakit=0.7.15=1
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cairo=1.16.0=h19f5f5c_2
  - certifi=2024.2.2=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - chardet=4.0.0=py39h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - conda=22.9.0=py39h06a4308_0
  - conda-package-handling=2.2.0=py39h06a4308_0
  - conda-package-streaming=0.9.0=py39h06a4308_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - curl=7.84.0=h5eee18b_0
  - cython=0.29.30=py39h6a678d5_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.7=py39h06a4308_0
  - fastp=0.22.0=h2e03b76_0
  - fastqc=0.11.8=1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - fontconfig=2.14.1=hef1e5e3_0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h7b6447c_0
  - gatk=3.8=hdfd78af_11
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gdbm=1.18=hd4cb3f1_4
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_0
  - glib=2.69.1=h4ff587b_1
  - glibc-common-amzn2-aarch64=2.26=5
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - h5py=3.6.0=py39ha0f2276_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.10.6=h3ffc7dd_1
  - htslib=1.11=hd3b49d5_2
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - joblib=1.2.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libboost=1.73.0=h28710b8_12
  - libcurl=7.84.0=h91b91d3_0
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm11=11.1.0=h9e868ea_6
  - libnghttp2=1.46.0=hce63b2e_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hecacb30_2
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - llvmlite=0.38.0=py39h4ff587b_0
  - lz4-c=1.9.4=h6a678d5_0
  - make=4.2.1=h1bed415_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.3=h5eee18b_3
  - networkx=2.8.4=py39h06a4308_0
  - numba=0.55.1=py39h51133e4_0
  - numexpr=2.8.3=py39hd2a5715_0
  - numpy=1.21.5=py39hf838250_3
  - numpy-base=1.21.5=py39h1e6e340_3
  - omp=1.0=0
  - openjdk=8.0.152=h7b6447c_3
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.2=py39h06a4308_0
  - pango=1.50.7=h05da053_0
  - parallel=20220922=ha770c72_0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - perl=5.34.0=h5eee18b_2
  - pixman=0.40.0=h7f8727e_1
  - py-boost=1.73.0=py39h51133e4_12
  - pycosat=0.6.6=py39h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_0
  - quspin=0.3.6=omp_py39h3c6ec7f_0
  - r-base=4.2.0=h1ae530e_0
  - r-bitops=1.0_7=r42h76d94ec_0
  - r-catools=1.18.2=r42h884c59f_0
  - r-cli=3.3.0=r42h884c59f_0
  - r-colorspace=2.0_3=r42h76d94ec_0
  - r-crayon=1.5.1=r42h6115d3f_0
  - r-digest=0.6.29=r42h884c59f_0
  - r-ellipsis=0.3.2=r42h76d94ec_0
  - r-fansi=1.0.3=r42h76d94ec_0
  - r-farver=2.1.0=r42h884c59f_0
  - r-ggplot2=3.3.6=r42h6115d3f_0
  - r-glue=1.6.2=r42h76d94ec_0
  - r-gplots=3.1.3=r42h6115d3f_0
  - r-gsalib=2.1=r42h142f84f_0
  - r-gtable=0.3.0=r42h6115d3f_0
  - r-gtools=3.9.2.1=r42h76d94ec_0
  - r-isoband=0.2.5=r42h884c59f_0
  - r-kernsmooth=2.23_20=r42h640688f_0
  - r-labeling=0.4.2=r42h6115d3f_0
  - r-lattice=0.20_45=r42h76d94ec_0
  - r-lifecycle=1.0.1=r42h142f84f_0
  - r-magrittr=2.0.3=r42h76d94ec_0
  - r-mass=7.3_57=r42h76d94ec_0
  - r-matrix=1.4_1=r42h76d94ec_0
  - r-mgcv=1.8_40=r42h76d94ec_0
  - r-munsell=0.5.0=r42h6115d3f_0
  - r-nlme=3.1_157=r42h640688f_0
  - r-pillar=1.7.0=r42h6115d3f_0
  - r-pkgconfig=2.0.3=r42h6115d3f_0
  - r-plyr=1.8.7=r42h884c59f_0
  - r-r6=2.5.1=r42h6115d3f_0
  - r-rcolorbrewer=1.1_3=r42h6115d3f_0
  - r-rcpp=1.0.8.3=r42h884c59f_0
  - r-reshape=0.8.9=r42h142f84f_0
  - r-rlang=1.1.1=r42h884c59f_0
  - r-scales=1.2.0=r42h6115d3f_0
  - r-tibble=3.1.7=r42h76d94ec_0
  - r-utf8=1.2.2=r42h76d94ec_0
  - r-vctrs=0.4.1=r42h884c59f_0
  - r-viridislite=0.4.0=r42h6115d3f_0
  - r-withr=2.5.0=r42h6115d3f_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_1
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - sambamba=0.6.6=2
  - samblaster=0.1.24=hc9558a2_3
  - samtools=1.6=h4da6232_1
  - scipy=1.11.4=py39heeff2f4_0
  - seqtk=1.3=h5bf99c6_3
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tktable=2.10=h3d55465_1
  - toolz=0.12.0=py39h06a4308_0
  - typing-extensions=4.9.0=py39h06a4308_1
  - typing_extensions=4.9.0=py39h06a4308_1
  - tzdata=2024a=h04d1e81_0
  - tzdata-amzn2-aarch64=2020d=5
  - urllib3=2.1.0=py39h06a4308_1
  - webencodings=0.5.1=py39h06a4308_1
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.12=h5eee18b_3
  - zstandard=0.19.0=py39h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - apbs==3.2.1
    - brian2==2.5.1
    - jinja2==3.1.2
    - markupsafe==2.1.1
    - mpmath==1.2.1
    - pyyaml==6.0.1
    - sympy==1.10.1
prefix: /home/apps/DL-conda
